#### Some basic playbooks

(1)

---
- hosts: all
  tasks:
      - name: install apache
        apt:
           name: apache2
           state: latest
        become: yes
      - name: index.html
        copy:
           content: "this is ansible playbook"
           dest: /var/www/html/index.hrml
        become: yes

####################################

(2)

---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
