###  simeple playbook that create a new folder under Desktop ###




---
- name: My first script     ### The name of the script 
  hosts: linux01     #### my host/s name 
  tasks:
    - name: create a new folder under Desktop
      file:
        path: /home/guy/Desktop/newfolder    #### Wherever you want the folder to be 
        state: directory    ### Type 
        mode: 0755
